// YouTube 데이터 관리 (자동 생성됨)

// 동영상 데이터
export const videos = [
    {
        id: 'video-1',
        title: 'NOMAD "LIGHTS ON" Performance Video',
        thumbnail: 'https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/insta-photo/250930%20(1).jpg',
        duration: '3:42',
        uploadDate: '1일 전',
        type: 'video'
    },
    {
        id: 'video-2',
        title: 'Behind The Scenes - NOMAD',
        thumbnail: 'https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/insta-photo/250923%20(1).jpg',
        duration: '5:21',
        uploadDate: '3일 전',
        type: 'video'
    },
    {
        id: 'video-3',
        title: 'NOMAD Dance Practice',
        thumbnail: 'https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/insta-photo/250914%20(1).jpg',
        duration: '4:15',
        uploadDate: '1주 전',
        type: 'video'
    },
    {
        id: 'video-4',
        title: 'NOMAD Concept Photo Shooting',
        thumbnail: 'https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/insta-photo/250823%20(1).jpg',
        duration: '2:58',
        uploadDate: '2주 전',
        type: 'video'
    },
    {
        id: 'video-5',
        title: 'NOMAD Interview',
        thumbnail: 'https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/insta-photo/250814%20(1).jpg',
        duration: '8:12',
        uploadDate: '3주 전',
        type: 'video'
    }
];

// Shorts 데이터 (자동 생성됨)
export const shorts = [
    {
        "id": "short-1",
        "title": "251128",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/251128.mp4",
        "duration": "0:00",
        "uploadDate": "1개월 전",
        "type": "shorts",
        "rawDate": "251128",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-2",
        "title": "251112",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/251112.mp4",
        "duration": "0:00",
        "uploadDate": "1개월 전",
        "type": "shorts",
        "rawDate": "251112",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-3",
        "title": "251031",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/251031.mp4",
        "duration": "0:00",
        "uploadDate": "2개월 전",
        "type": "shorts",
        "rawDate": "251031",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-4",
        "title": "251027",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/251027.mp4",
        "duration": "0:00",
        "uploadDate": "2개월 전",
        "type": "shorts",
        "rawDate": "251027",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-5",
        "title": "251001",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/251001.mp4",
        "duration": "0:00",
        "uploadDate": "3개월 전",
        "type": "shorts",
        "rawDate": "251001",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-6",
        "title": "250916",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250916.mp4",
        "duration": "0:00",
        "uploadDate": "3개월 전",
        "type": "shorts",
        "rawDate": "250916",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-7",
        "title": "250901",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250901.mp4",
        "duration": "0:00",
        "uploadDate": "4개월 전",
        "type": "shorts",
        "rawDate": "250901",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-8",
        "title": "250810",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250810.mp4",
        "duration": "0:00",
        "uploadDate": "4개월 전",
        "type": "shorts",
        "rawDate": "250810",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-9",
        "title": "250618",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250618.mp4",
        "duration": "0:00",
        "uploadDate": "6개월 전",
        "type": "shorts",
        "rawDate": "250618",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-10",
        "title": "250601",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250601.mp4",
        "duration": "0:00",
        "uploadDate": "7개월 전",
        "type": "shorts",
        "rawDate": "250601",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-11",
        "title": "250528",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250528.mp4",
        "duration": "0:00",
        "uploadDate": "7개월 전",
        "type": "shorts",
        "rawDate": "250528",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-12",
        "title": "250521",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250521.mp4",
        "duration": "0:00",
        "uploadDate": "7개월 전",
        "type": "shorts",
        "rawDate": "250521",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-13",
        "title": "250505",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250505.mp4",
        "duration": "0:00",
        "uploadDate": "8개월 전",
        "type": "shorts",
        "rawDate": "250505",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-14",
        "title": "250504",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250504.mp4",
        "duration": "0:00",
        "uploadDate": "8개월 전",
        "type": "shorts",
        "rawDate": "250504",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-15",
        "title": "250420",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250420.mp4",
        "duration": "0:00",
        "uploadDate": "8개월 전",
        "type": "shorts",
        "rawDate": "250420",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-16",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250402-2.mp4",
        "duration": "0:00",
        "uploadDate": "9개월 전",
        "type": "shorts",
        "rawDate": "250402",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-17",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250402-1.mp4",
        "duration": "0:00",
        "uploadDate": "9개월 전",
        "type": "shorts",
        "rawDate": "250402",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-18",
        "title": "250329",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250329.mp4",
        "duration": "0:00",
        "uploadDate": "9개월 전",
        "type": "shorts",
        "rawDate": "250329",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-19",
        "title": "250327",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250327.mp4",
        "duration": "0:00",
        "uploadDate": "9개월 전",
        "type": "shorts",
        "rawDate": "250327",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-20",
        "title": "250320",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250320.mp4",
        "duration": "0:00",
        "uploadDate": "9개월 전",
        "type": "shorts",
        "rawDate": "250320",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-21",
        "title": "250319",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250319.mp4",
        "duration": "0:00",
        "uploadDate": "9개월 전",
        "type": "shorts",
        "rawDate": "250319",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-22",
        "title": "250318",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250318.mp4",
        "duration": "0:00",
        "uploadDate": "9개월 전",
        "type": "shorts",
        "rawDate": "250318",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-23",
        "title": "250317",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250317.mp4",
        "duration": "0:00",
        "uploadDate": "9개월 전",
        "type": "shorts",
        "rawDate": "250317",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-24",
        "title": "250303",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250303.mp4",
        "duration": "0:00",
        "uploadDate": "10개월 전",
        "type": "shorts",
        "rawDate": "250303",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-25",
        "title": "250301",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250301.mp4",
        "duration": "0:00",
        "uploadDate": "10개월 전",
        "type": "shorts",
        "rawDate": "250301",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-26",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250228-2.mp4",
        "duration": "0:00",
        "uploadDate": "10개월 전",
        "type": "shorts",
        "rawDate": "250228",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-27",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250228-1.mp4",
        "duration": "0:00",
        "uploadDate": "10개월 전",
        "type": "shorts",
        "rawDate": "250228",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-28",
        "title": "250226",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250226.mp4",
        "duration": "0:00",
        "uploadDate": "10개월 전",
        "type": "shorts",
        "rawDate": "250226",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-29",
        "title": "250220",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250220.mp4",
        "duration": "0:00",
        "uploadDate": "10개월 전",
        "type": "shorts",
        "rawDate": "250220",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-30",
        "title": "250217",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250217.mp4",
        "duration": "0:00",
        "uploadDate": "10개월 전",
        "type": "shorts",
        "rawDate": "250217",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-31",
        "title": "250214",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250214.mp4",
        "duration": "0:00",
        "uploadDate": "10개월 전",
        "type": "shorts",
        "rawDate": "250214",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-32",
        "title": "250213",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250213.mp4",
        "duration": "0:00",
        "uploadDate": "10개월 전",
        "type": "shorts",
        "rawDate": "250213",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-33",
        "title": "250212",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250212.mp4",
        "duration": "0:00",
        "uploadDate": "10개월 전",
        "type": "shorts",
        "rawDate": "250212",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-34",
        "title": "250211",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250211.mp4",
        "duration": "0:00",
        "uploadDate": "10개월 전",
        "type": "shorts",
        "rawDate": "250211",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-35",
        "title": "250205",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250205.mp4",
        "duration": "0:00",
        "uploadDate": "11개월 전",
        "type": "shorts",
        "rawDate": "250205",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-36",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250202-2.mp4",
        "duration": "0:00",
        "uploadDate": "11개월 전",
        "type": "shorts",
        "rawDate": "250202",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-37",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250202-1.mp4",
        "duration": "0:00",
        "uploadDate": "11개월 전",
        "type": "shorts",
        "rawDate": "250202",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-38",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250128-2.mp4",
        "duration": "0:00",
        "uploadDate": "11개월 전",
        "type": "shorts",
        "rawDate": "250128",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-39",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250128-1.mp4",
        "duration": "0:00",
        "uploadDate": "11개월 전",
        "type": "shorts",
        "rawDate": "250128",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-40",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250111-2.mp4",
        "duration": "0:00",
        "uploadDate": "12개월 전",
        "type": "shorts",
        "rawDate": "250111",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-41",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250111-1.mp4",
        "duration": "0:00",
        "uploadDate": "12개월 전",
        "type": "shorts",
        "rawDate": "250111",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-42",
        "title": "250105",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/250105.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "250105",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-43",
        "title": "241229",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241229.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241229",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-44",
        "title": "241228",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241228.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241228",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-45",
        "title": "241227",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241227.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241227",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-46",
        "title": "241226",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241226.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241226",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-47",
        "title": "241224",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241224.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241224",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-48",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241221-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241221",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-49",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241221-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241221",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-50",
        "title": "241220",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241220.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241220",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-51",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241219-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241219",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-52",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241219-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241219",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-53",
        "title": "241214",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241214.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241214",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-54",
        "title": "241212",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241212.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241212",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-55",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241210-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241210",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-56",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241210-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241210",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-57",
        "title": "241209",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241209.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241209",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-58",
        "title": "241204",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241204.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241204",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-59",
        "title": "241202",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241202.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241202",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-60",
        "title": "241129",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241129.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241129",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-61",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241128-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241128",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-62",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241128-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241128",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-63",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241127-3.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241127",
        "postNum": 3,
        "description": ""
    },
    {
        "id": "short-64",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241127-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241127",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-65",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241127-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241127",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-66",
        "title": "241126",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241126.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241126",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-67",
        "title": "241125",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241125.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241125",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-68",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241122-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241122",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-69",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241122-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241122",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-70",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241121-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241121",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-71",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241121-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241121",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-72",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241119-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241119",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-73",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241119-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241119",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-74",
        "title": "241118",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241118.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241118",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-75",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241116-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241116",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-76",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241116-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241116",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-77",
        "title": "241115",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241115.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241115",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-78",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241114-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241114",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-79",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241114-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241114",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-80",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241111-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241111",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-81",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241111-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241111",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-82",
        "title": "241110",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241110.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241110",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-83",
        "title": "241108",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241108.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241108",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-84",
        "title": "241107",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241107.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241107",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-85",
        "title": "241106",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241106.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241106",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-86",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241105-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241105",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-87",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241105-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241105",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-88",
        "title": "241104",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241104.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241104",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-89",
        "title": "241103",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241103.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241103",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-90",
        "title": "241029",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241029.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241029",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-91",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241028-3.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241028",
        "postNum": 3,
        "description": ""
    },
    {
        "id": "short-92",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241028-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241028",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-93",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241028-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241028",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-94",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241025-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241025",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-95",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241025-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241025",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-96",
        "title": "241023",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241023.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241023",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-97",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241021-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241021",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-98",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241021-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241021",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-99",
        "title": "241019",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241019.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241019",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-100",
        "title": "241016",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241016.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241016",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-101",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241015-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241015",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-102",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241015-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241015",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-103",
        "title": "241011",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241011.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241011",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-104",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241010-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241010",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-105",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241010-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241010",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-106",
        "title": "241009",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/241009.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "241009",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-107",
        "title": "240929",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240929.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240929",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-108",
        "title": "240927",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240927.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240927",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-109",
        "title": "240922",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240922.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240922",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-110",
        "title": "240916",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240916.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240916",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-111",
        "title": "240915",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240915.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240915",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-112",
        "title": "240827",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240827.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240827",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-113",
        "title": "240814",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240814.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240814",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-114",
        "title": "240803",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240803.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240803",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-115",
        "title": "240731",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240731.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240731",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-116",
        "title": "240722",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240722.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240722",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-117",
        "title": "240625",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240625.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240625",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-118",
        "title": "240623",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240623.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240623",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-119",
        "title": "240621",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240621.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240621",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-120",
        "title": "240618",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240618.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240618",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-121",
        "title": "240606",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240606.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240606",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-122",
        "title": "240603",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240603.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240603",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-123",
        "title": "240529",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240529.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240529",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-124",
        "title": "240528",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240528.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240528",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-125",
        "title": "240527",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240527.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240527",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-126",
        "title": "240523",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240523.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240523",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-127",
        "title": "240510",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240510.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240510",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-128",
        "title": "240505",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240505.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240505",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-129",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240430-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240430",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-130",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240430-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240430",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-131",
        "title": "240417",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240417.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240417",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-132",
        "title": "240408",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240408.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240408",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-133",
        "title": "240329",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240329.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240329",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-134",
        "title": "240325",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240325.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240325",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-135",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240320-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240320",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-136",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240320-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240320",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-137",
        "title": "240319",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240319.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240319",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-138",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240317-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240317",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-139",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240317-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240317",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-140",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240316-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240316",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-141",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240316-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240316",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-142",
        "title": "240314",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240314.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240314",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-143",
        "title": "240313",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240313.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240313",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-144",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240308-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240308",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-145",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240308-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240308",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-146",
        "title": "240306",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240306.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240306",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-147",
        "title": "240305",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240305.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240305",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-148",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240304-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240304",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-149",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240304-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240304",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-150",
        "title": "240302",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240302.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240302",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-151",
        "title": "240301",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240301.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240301",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-152",
        "title": "240207",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240207.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240207",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-153",
        "title": "240201",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240201.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240201",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-154",
        "title": "240129",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240129.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240129",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-155",
        "title": "240124",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240124.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240124",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-156",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240122-2.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240122",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-157",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240122-1.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240122",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-158",
        "title": "240117",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240117.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240117",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-159",
        "title": "240115",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/240115.mp4",
        "duration": "0:00",
        "uploadDate": "1년 전",
        "type": "shorts",
        "rawDate": "240115",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-160",
        "title": "231231",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/231231.mp4",
        "duration": "0:00",
        "uploadDate": "2년 전",
        "type": "shorts",
        "rawDate": "231231",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-161",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/231228-2.mp4",
        "duration": "0:00",
        "uploadDate": "2년 전",
        "type": "shorts",
        "rawDate": "231228",
        "postNum": 2,
        "description": ""
    },
    {
        "id": "short-162",
        "title": "",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/231228-1.mp4",
        "duration": "0:00",
        "uploadDate": "2년 전",
        "type": "shorts",
        "rawDate": "231228",
        "postNum": 1,
        "description": ""
    },
    {
        "id": "short-163",
        "title": "231226",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/231226.mp4",
        "duration": "0:00",
        "uploadDate": "2년 전",
        "type": "shorts",
        "rawDate": "231226",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-164",
        "title": "231225",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/231225.mp4",
        "duration": "0:00",
        "uploadDate": "2년 전",
        "type": "shorts",
        "rawDate": "231225",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-165",
        "title": "231224",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/231224.mp4",
        "duration": "0:00",
        "uploadDate": "2년 전",
        "type": "shorts",
        "rawDate": "231224",
        "postNum": null,
        "description": ""
    },
    {
        "id": "short-166",
        "title": "231223",
        "thumbnail": "https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/reels/231223.mp4",
        "duration": "0:00",
        "uploadDate": "2년 전",
        "type": "shorts",
        "rawDate": "231223",
        "postNum": null,
        "description": ""
    }
];

// 채널 정보
export const channelInfo = {
    name: 'NOMAD',
    handle: '@NOMAD_is_here',
    subscribers: '9.16만',
    videoCount: '166',
    description: 'NOMAD OFFICIAL YouTube Channel',
    banner: 'https://raw.githubusercontent.com/DOY-is-here/doy-is-here.github.io/main/insta-photo/250930%20(4).jpg'
};

// 탭별 데이터 가져오기
export function getContentByTab(tab) {
    switch(tab) {
        case 'home':
            return videos;
        case 'videos':
            return videos;
        case 'shorts':
            return shorts;
        case 'playlists':
            return [];
        case 'channels':
            return [];
        case 'about':
            return [];
        default:
            return videos;
    }
}
